service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
    seed:
      local:
        sources:
          - table: personasTable

plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-dynamodb-local

functions:
  api:
    handler: src/functions/fusionados.handler
    events:
      - httpApi:
          path: /fusionados
          method: get

resources:
  Resources:
    ExampleTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: personasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
