service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

plugins:
    - serverless-plugin-typescript
    - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
