service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  
  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: '$request.header.Authorization'
        issuerUrl: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_XiO86pRpM'
        audience:
          - 6bfp1smukujvm2cqabucaaplqt
    logs:
      fullExecutionData: true
      retentionInDays: 7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource:
        - arn:aws:cognito-idp:us-east-1:296062591296:userpool/us-east-1_XiO86pRpM 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:296062591296:table/personaCache
        - arn:aws:dynamodb:us-east-1:296062591296:table/personaCache/*
        - arn:aws:dynamodb:us-east-1:296062591296:table/planetaCache
        - arn:aws:dynamodb:us-east-1:296062591296:table/planetaCache/*
        - arn:aws:dynamodb:us-east-1:296062591296:table/personasTable
        - arn:aws:dynamodb:us-east-1:296062591296:table/personasTable/*

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
    seed:
      local:
        sources:
          - table: personasTable

plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-dynamodb-local

functions:
  fusionados:
    handler: src/functions/fusionados.handler
    events:
      - httpApi:
          path: /fusionados
          method: get
          authorizer: cognitoAuthorizer
  save:
    handler: src/functions/save.handler
    events:
      - httpApi:
          path: /save
          method: post
  historial:
    handler: src/functions/historial.handler
    events:
      - httpApi:
          path: /obtener
          method: get
          authorizer: cognitoAuthorizer
  cache:
    handler: src/functions/cache.handler
    events:
      - httpApi:
          path: /cache
          method: get
          authorizer: cognitoAuthorizer

  auth:
    handler: src/functions/auth.handler
    events:
      - httpApi:
          path: /auth
          method: post

resources:
  Resources:
    PersonaTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: personasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PlanetaCacheTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: planetaCache
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    PersonaCacheTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: personaCache
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
